apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ilo4-metrics-exporter.fullname" . }}
  labels:
  {{- include "ilo4-metrics-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "ilo4-metrics-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "ilo4-metrics-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ilo4-metrics-exporter.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - args:
            - --production
            - --listen=:2112
            {{- if .Values.ilo.certificate }}
            - --ilo-certificate-path=/certificate.pem
            {{- end }}
            - --ilo-credentials-path=/login.json
            {{- range $a := .Values.extraArgs }}
            - {{ $a }}
          {{- end }}
          env:
            - name: ILO_URL
              value: {{ .Values.ilo.url }}
          name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 2112
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.ilo.certificate }}
            - name: config
              mountPath: /certificate.pem
              subPath: certificate.pem
              readOnly: true
            {{- end }}
            - name: secret
              mountPath: /login.json
              subPath: {{ .Values.ilo.login.secretKey }}
              readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: {{ .Values.ilo.login.secretName | default (include "ilo4-metrics-exporter.fullname" .) }}
        - name: config
          configMap:
            name: {{ include "ilo4-metrics-exporter.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}

  {{- end }}
